### ISSUE TITLE
onsubmit testing - final closure

### ISSUE THREAD

**Issue by arfa2** [hsnayd/validetta#28]
Hi Hasan, I am close but have still to resolve my aims. I hope you have time to help.

1 - I see your point with the ``this.handler = 'pending';`` and am working with that line active.
2 - I am aiming to recode all my forms and am working with one of the more simple - a sign-up.
3 - I want to validate and submit data to file while maintaining page state
4 - I see the asynchronous (one by one) nature of validetta so have been using a CSV temp file to record each field as it is validated. Works fine - **providing** that the submit button is not clicked while there are errors.
5 - Here is an example
http://bodhinyanarama.net.nz/news/subScribeTest.php
I have used ``$_SESSION`` to track state toggling from XYZ to > F [first] L [last] M [mail]
6 - If you enter data for 'first' then shift focus you can see this updated in:
http://bodhinyanarama.net.nz/news/testTMP.txt
Then enter data for second > test in TMP.txt
Then click submit. You will see the error as FLZ [no email so Z has not been changed to M]
7 - If I go back and change first or last these changes are visible in TMP.txt But if I enter a valid email that change is registered in TMP.txt -- ie. the remote call is working. **BUT**
8 - No way can I get the onVaild to fire.
9 - If you reload the form and enter all data correctly and then click submit -- **YES** > Bingo! > onValid message is printed.
check database result"
http://bodhinyanarama.net.nz/news/test_news.db

What is blocking the clearance of the submit error - valid => false ?
Or is there something else I am missing?

code:
http://bodhinyanarama.net.nz/news/subScribeTest.txt [the form]
http://bodhinyanarama.net.nz/news/subScribeINTest.txt [remote php]

**Comment by arfa2** [comment]
I continue trying to get this working. I reread your comments on #27...
1 - validate a field realtime - yes
2 - only containing the properties "valid" and "message" - yes
3 - Remote validation is only check a fileld is a valid or not - Yes, but your example shows php calculation_action. I figure opening a file to test against or writing back to a file is just an extension of your example. It works - testing errors realtime - but breaks on click submit. 

>> There is much about jquery that is new to me so I apologise for not being totally clear. I have been trying to learn - particularly checkRemote and the issue of caching & xhr.

line 262 ``if( e.type !== 'submit' )... elseif...`` there are 3 options: pending, error, onValid
I have updated my example and set an ``alert('each option');`` to test submit status.
The sequence in my post...
http://bodhinyanarama.net.nz/news/subScribeTest.php
clearly shows us stuck at ``alert='handler pending'``

I have been trawling the net and trying to understand your code. Any suggestions would help. Thanks.

**Comment by arfa2** [comment]
I wonder if this has been read? I figure you are the only likely reader Hasan :)) It has been several days. I have tried as much as I can and wonder "where to from here?" It seems to me that it is *almost there* -- but, I concede my limited knowledge.

You may not have built validetta to do this but... it seems it can - but conditionally... which is not good enough for code.

I still ask... **why, when all fields are correct does onSubmit hold 'pending?'**
Quite likely something in my code -- but, possibly a tweak in your code would square it off?

After many hours work on this I can't think of what else to try. Can you please (politely :) tell me "enough" or... suggest something or... recommend a script that can validate with remote testing-writing [ouch?]

I have lots of time to learn.
thanks

**Comment by hsnayd** [comment]
Hi @arfa2 

I really want to help you. but as I said before, these days I could not take care of this place.

I have reviewed your examples. And I did try on my local server. Yes you are right. There's something wrong in validetta v1.0.0. Then when I did try with validetta v1.0.1 such an error did not occur.

Can you try with this version

https://github.com/hsnayd/validetta/tree/develop

Sory for late reply.

**Comment by hsnayd** [comment]
You have to use this way in new version

```js
  $(function(){
    $('#exm').validetta({
      realTime : true,
      onValid : function( event ){
        // Valid !!
        event.preventDefault();
      },
      validators: {
        remote : {
          check_username : {
            type : 'POST',
            url : 'subScribeINTest.php',
            datatype : 'json'
          }
        }
      }
    });
  });
```

**Comment by arfa2** [comment]
No problem about "late reply". My development path is very flexible and I suspect you are busy (as well as health and such) -- most people are.

I am very happy to hear from you. I had been considering alternatives but... your work is basically clean and solid and hopefully we can find a way. I will enjoy trying 1.0.1
thank you

**Comment by arfa2** [comment]
I have spent more time with this and can't (sadly) see any difference.
I have updated the form:
http://bodhinyanarama.net.nz/news/subScribeTest.php
and simplified my remote file
http://bodhinyanarama.net.nz/news/subScribeINTest.txt
so that only the ``$_SESSION['track']`` is being considered. 

The result is the same:
fill out 'first' and click submit - the 'subscribe' error == FYZ
fill out 'first' and 'last' and  'subscribe' error == FLZ
fill out 'email' and 'first' and 'subscribe' error == FYM
fill out all fields correctly and onValid fires 'OK'

I notice that with 'OK' that all fields are still filled with data. If I click submit again there is no action. 
There some caching going on here that my limited js can't isolate.

I tried setting ``$response=''; $track='';`` at the top of subScribeINTest..php hoping it would flush $line for the ``isset($_POST['signUp']`` but... no change.

I will try a few more things as the come to my mind but - this is your baby Hasan. I look forward to **any** thoughts or suggestions you might have that I could try. The code is cool - just needs a wee fix :)

**Comment by arfa2** [comment]
I know your time here is limited but I thought to keep you posted as I progress.

I think the main problem has been that I have been treating ``<input type='submit' ... >`` as a regular input. Yes, it is an input and will write an error bubble and all but - it is used in your script with special characteristics. I have tested not calling- *remote on submit* before but I suspect there were other errors. I am now cutting *everything* back to the simplest structure possible and am adding elements.

>>Bottom line -- I think the new version is working fine. I need to do a bit more testing to be sure of 100% results.

I would be curious to have **your thoughts on writing the completed form to file/db** How, when were you thinking do this?

I was interested to see that you have added ``bubblePosition`` in this new version. It is possible to position *left* setting ``bubbleGapLeft : -222,`` (or the width of the input) but I will re-write my #26 to offer ``bubblePosition: left,``

It takes time to get the world into the shape we want.
I hope you are well...

**Comment by hsnayd** [comment]
Hi @arfa2 

Have you tested completely ? Do you have any problem ?

> I was interested to see that you have added bubblePosition in this new version.

Yes v1.0.1 supports bubblePosition bottom and left, I will add right and top on next versiyon
