### ISSUE TITLE
submit form via php

### ISSUE THREAD

**Issue by pedrosmmc** [hsnayd/validetta#29]
Hi!
Great "validetta" hsnayd!!
I'm just havin an issue on sending the form via php without comment the "event.preventDefault();" on the "onValid" option.
What I would like to do is to send the form without refreshing the entire page, because that will hide the final validation feedback.
Really need your expertise on this one.
I tried with this with no good returning:

onValid : function( event ) {
        event.preventDefault();
        $('#alert').empty()
            .append('<div class="alert alert-success">Nice <b>' + name1.value + '</b>!</div>');
        $("#form").submit(function() {
          $.post($(this).attr("action"), $(this).serialize(), function(data){});
          return false;
        });
    }

Thanks for your time.
Beste regards,
Pedro Coelho.

**Comment by hsnayd** [comment]
Hi @pedrosmmc. Im glad you love it. 

Did you examine this example ?
[http://lab.hasanaydogdu.com/validetta/demo/ajax.html](http://lab.hasanaydogdu.com/validetta/demo/ajax.html)

**Comment by pedrosmmc** [comment]
Hello @hsnayd,
Now i can see :D
Solved. 
Yes I loved it, and know even more.
Keep up the good work!
