### ISSUE TITLE
Sending a file

### ISSUE THREAD

**Issue by pedrosmmc** [hsnayd/validetta#32]
<p>Hi Hsnayd!</p>
<p>I'm trying to send a file via email within a form and use the callbacks to deal with it, but without success.</p>
<p>Something like this...</p>

<code>onValid : function( event ) {</code>
<code>    event.preventDefault();</code>
<code>    $.ajax({</code>
<code>        type : 'POST',</code>
<code>        url : 'send.php',</code>
<code>        data : $('form').serialize(),</code>
<code>        success: function() {</code>
<code>            alert("Success!");</code>
<code>        }</code>
<code>    });</code>
 <code>},</code>

<p>Can't you give-me some hints on these?</p>
<p>Thanx a lot. Best regards, Pedro Coelho.</p>

**Comment by hsnayd** [comment]
Hi @pedrosmmc 

You cant transfer a file with ajax request. This is a file upload issue. Maybe this link can help you.

http://stackoverflow.com/questions/166221/how-can-i-upload-files-asynchronously

Thank you.

**Comment by pedrosmmc** [comment]
Great thanx!
Notice your last version changes.
Very nice job. Keep it up!
