### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by movingwater** [hsnayd/validetta#35]
The regular expression to validate email addresses seems to the see an address like asdf@dasdf as a valid address.

if you change the RegExp on line 19 to:
```javascript
/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
```
an address like the one above doesn't pass the validation.

**Comment by hsnayd** [comment]
Hi Jonathan
Validetta uses [standart regular expression of HTML5 email validation](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address)
if you need more complex email validation, you can use [regExp validator](http://lab.hasanaydogdu.com/validetta/#checkingMethods)
Thank you
