### ISSUE TITLE
Form being sent when showing modal element

### ISSUE THREAD

**Issue by gustavosuzukawa** [hsnayd/validetta#37]
When showing a modal element (I am using bootstrap) the submit event is being triggered. The function inside "onValid" is executed, even with "realTime : false".

Is this the correct behavior?

If a form's fields are completely correct and the modal is shown, the form is submitted. Although that is not my intention.

**Comment by hsnayd** [comment]
Hi @gustavosuzukawa 
Can you show me an example on [jsfiddle](http://jsfiddle.net/)

**Comment by gustavosuzukawa** [comment]
My code was wrong, the button responsible for showing the modal did no have the "type=button"

So everytime I clicked it the form was being sent.
Now the behavior is correct.

The plugin is excellent, thank you!
