### ISSUE TITLE
Form fields not working on Android

### ISSUE THREAD

**Issue by rjpedrosa** [hsnayd/validetta#39]
Hi,

For some reason, when I activate Validetta on my form, the input fields stop working on Android browsers. Taping on a field will make the page scroll up a little bit and does not focus on it.

Here's the form: m: http://community-tu.org/support-safer-justice-sector-mp/

Any idea what the issue could be?

Thanks!

**Comment by hsnayd** [comment]
Hi @rjpedrosa

I didnt see `data-validetta` attribute on your input fields. Check [this link](http://lab.hasanaydogdu.com/validetta/#documentation) for more information about how validetta does work.

Also each field must be wrapped by an element like `<div>`

Thanks

**Comment by rjpedrosa** [comment]
Hi,

Sorry, you might have visited the page when I was trying to fix it.
Have a look at it now. Also wrapped each field in a div.

Thanks

**Comment by hsnayd** [comment]
Hi @rjpedrosa 

Can you show me an example on [jsfiddle](https://jsfiddle.net/)

**Comment by rjpedrosa** [comment]
Is is not manageable to create a jsFiddle as this is on a Wordpress website and has many includes and CSS on different files. Can't you check  on this page? http://community-tu.org/support-safer-justice-sector-mp/
I am no sure the problem is your plugin, but when I disable it, the form works fine on Android. But can't find the conflict...
It would be great if you could help me.

**Comment by hsnayd** [comment]
`http://community-tu.org/wp-content/themes/community/js/ui.js`
This plugin listening submit event. Cant you disable it and try again ?

**Comment by rjpedrosa** [comment]
I've have disabled the `$("form").submit(function(e)...` bit, but still not working... :(

**Comment by hsnayd** [comment]
You have z-index problem

**Comment by rjpedrosa** [comment]
Where?
I've added this and didn't solve the problem:

'.general-form,
.general-form input,
.general-form textarea,
.general-form button {
	position:relative !important;
	z-index:999999999999999 !important;
}'

**Comment by hsnayd** [comment]
I do not know exactly where the error is caused, but open the link with chorme and open developer Tools window, active device mode, select any android device and remove `<div id="responsive-menu"><div>` with developer tools. Then you will see the form is working successfully.

This issue seems not related with validetta. 

Thank you.

**Comment by rjpedrosa** [comment]
Thanks, that helped. Conflict with my responsive menu.
Sorted now.

Cheers!
