### ISSUE TITLE
Specify error template

### ISSUE THREAD

**Issue by risker** [hsnayd/validetta#40]
I have a use case where I need to add an icon in front of the error message. I'd like to do this globally by defining a template in the initialization settings.

For example, the settings could look like:
`templates: {
		errorTemplate: '<span class="%errorTemplateClass%"><span class="my-icon"></span>%errorMessage%</span>'
	}`

**Comment by hsnayd** [comment]
Hi @risker 

Its not possibble for current version, It may be considered in future versions.
In your case, you can define icon to ::before pseudo-element if It possible.

Thank you.
